// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfnvwrzqBSNwUdK_nJXGOWeeiRLhu4bM',
    appId: '1:704032755423:web:b7bfd167e998eed688236a',
    messagingSenderId: '704032755423',
    projectId: 'controleabastecimento-b000',
    authDomain: 'controleabastecimento-b000.firebaseapp.com',
    storageBucket: 'controleabastecimento-b000.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQCxnJyXvA0qE7tjvXKWMWQpaBTGLgng',
    appId: '1:704032755423:android:260c59e022bf6a8788236a',
    messagingSenderId: '704032755423',
    projectId: 'controleabastecimento-b000',
    storageBucket: 'controleabastecimento-b000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAkbWZyKZChvB7K5DFRb8qr0iyrxIX2PA',
    appId: '1:704032755423:ios:0bb8c0212cfdbe8288236a',
    messagingSenderId: '704032755423',
    projectId: 'controleabastecimento-b000',
    storageBucket: 'controleabastecimento-b000.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAkbWZyKZChvB7K5DFRb8qr0iyrxIX2PA',
    appId: '1:704032755423:ios:0bb8c0212cfdbe8288236a',
    messagingSenderId: '704032755423',
    projectId: 'controleabastecimento-b000',
    storageBucket: 'controleabastecimento-b000.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmfnvwrzqBSNwUdK_nJXGOWeeiRLhu4bM',
    appId: '1:704032755423:web:0e93ffefa1e6871188236a',
    messagingSenderId: '704032755423',
    projectId: 'controleabastecimento-b000',
    authDomain: 'controleabastecimento-b000.firebaseapp.com',
    storageBucket: 'controleabastecimento-b000.firebasestorage.app',
  );
}
